reddit-on-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs, except: :destroy
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :comments, only: :create
  
end

reddit-on-rails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  url        :string
#  content    :text
#  author_id  :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  
  belongs_to :author,
  foreign_key: :author_id,
  class_name: :User,
  inverse_of: :posts
  
  has_many :post_subs,
  primary_key: :id,
  foreign_key: :post_id,
  class_name: :PostSub,
  inverse_of: :post
  
  has_many :subs,
    through: :post_subs,
    source: :sub
    
  has_many :comments
end

reddit-on-rails/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_log_in!
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    # @post.sub_id = params[:sub_id]
    # @post.sub_ids = params[]
    @post.author_id = current_user.id
    
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = current_user.posts.find(params[:id])
    
    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to sub_url(@post.sub_id)
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
  
end

reddit-on-rails/app/helpers/posts_helper.rb
module PostsHelper
end

reddit-on-rails/app/views/posts/new.html.erb
<h3>Add Post</h3>
<form action="<%= posts_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">  

  
  <% Sub.all.each do |sub| %>
    <input type="checkbox" name="post[sub_ids][]" value ="<%= sub.id %>"> <%= sub.title %><br>
    <!-- if checked
    [subids] << sub.id -->
    
  <% end %>
  
  <label>
    Title
    <input type="text" name="post[title]" value="">
  </label>
  <br>
  <label>
    URL
    <input type="text" name="post[url]" value="">
  </label>
  <br>
  <label>
    Content
    <textarea name="post[content]" rows="8" cols="80"></textarea>
    </label>
      <br>
    <input type="submit" name="" value="Create New Post!">
  
</form>

reddit-on-rails/app/views/posts/show.html.erb
<h2> <a href="<%= post_url(@post) %>"><%= @post.title %></a>
by <%= User.find(@post.author_id).username %> </h2>

Content:
<%= @post.content %>
<br>
Subs:

<ul>
<% @post.subs.each do |sub| %>
  <li><a href="<%= sub_url(sub) %>"><%= Sub.find(sub.id).title%></a></li>
<% end %>
</ul>