reddit-on-rails/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  
  resources :subs, except: :destroy
  resources :posts, only: [:new, :create, :edit, :update, :show, :destroy]
  resources :comments, only: :create
  
end

reddit-on-rails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :bigint(8)        not null, primary key
#  title       :string           not null
#  description :text             not null
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, presence: true
  
  belongs_to :moderator,
  foreign_key: :mod_id,
  class_name: :User,
  inverse_of: :subs
  
  has_many :post_subs,
  primary_key: :id,
  foreign_key: :sub_id,
  class_name: :PostSub,
  inverse_of: :sub

  has_many :posts,
    through: :post_subs,
    source: :post,
    inverse_of: :subs
  
end

reddit-on-rails/app/controllers/subs_controller.rb
class SubsController < ApplicationController
  before_action :require_log_in!
  
  def new
    @sub = Sub.new
  end
  
  def create
    @sub = Sub.new(sub_params)
    @sub.mod_id = current_user.id
    if @sub.save
      redirect_to subs_url
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end
  
  def index
    @subs = Sub.all
  end
  
  def show
    @sub = Sub.find(params[:id])
  end
  
  def edit
    @sub = Sub.find(params[:id])
  end
  
  def update
    @sub = Sub.find(params[:id])
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit  
    end
  end
  
  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
    
end

reddit-on-rails/app/helpers/subs_helper.rb
module SubsHelper
end

reddit-on-rails/app/views/subs/edit.html.erb
<h1>Edit Sub</h1>

<form action="<%= sub_url(@sub) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="patch">
  
  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  
  <input type="submit" name="" value="Edit Sub">
  
  
</form>

reddit-on-rails/app/views/subs/index.html.erb
<div class = "border">
<a href="<%= new_sub_url %>">Create a new sub!</a>

<h1>All the subs!</h1>

<% @subs.each do |sub| %>
  <ul>
    <li> <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
      <form action="<%= edit_sub_url(sub) %>" method="post">
        <input type="hidden" name="_method" value="get">
        <input type="submit" name="" value="Edit Sub">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
      </form> 

    </li>
    
  </ul>
<% end %>

</div>

reddit-on-rails/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form action="<%= subs_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>
    Title
    <input type="text" name="sub[title]" value="<%= @sub.title %>">
  </label>
  
  <label>
    Description
    <input type="text" name="sub[description]" value="<%= @sub.description %>">
  </label>
  
  <input type="submit" name="" value="Create New Sub!">
  
  
</form>

reddit-on-rails/app/views/subs/show.html.erb
<h1><%= @sub.title %></h1>

<h3>Description </h3>
<%= @sub.description %>
<br>

<ul>
<% @sub.posts.each do |post| %>
    <li> <a href="<%= post_url(post) %>"><%= post.title %></a></li>
<% end %>
</ul>

<form class="" action="<%= new_post_url %>" method="post">
  <input type="hidden" name="_method" value="get">
  <input type="submit" name="" value="Make New Post!">
</form>